import Foundation
import SuttoDomain
import SuttoOperations
import os

/// File-based ``SuttoOperations/SpaceCollectionRepository`` persisting to
/// JSON files, by default under `~/Library/Application Support/Sutto/`.
///
/// Mirrors the GNOME `FileSpaceCollectionRepository`
/// (`infra/file/file-space-collection-repository.ts`): each storage document
/// is a JSON array of collections in the `RawSpaceCollection` format (the
/// synthesized `Codable` of ``SuttoDomain/SpaceCollection`` reproduces it
/// key for key — see the schema PR), presets and customs live in separate
/// files, and the file names are kept identical
/// (`preset-space-collections.sutto.json` /
/// `custom-space-collections.sutto.json`, from the GNOME
/// `infra/constants.ts`) so a user can carry the files between the two apps
/// by hand. The GNOME app stores them in the extension data dir
/// (`~/.local/share/gnome-shell/extensions/<uuid>/`); Application Support
/// is the macOS analogue.
///
/// Load failures degrade to an empty list with a log line, exactly like the
/// GNOME repository: a missing file is the normal first run, and a corrupt
/// file must not brick the app (a corrupt preset file is regenerated by the
/// next ensure, a corrupt custom file leaves the presets available).
public final class FileSpaceCollectionRepository: SpaceCollectionRepository {
    /// File names shared with the GNOME version
    /// (`PRESET_SPACE_COLLECTIONS_FILE_NAME` /
    /// `CUSTOM_SPACE_COLLECTIONS_FILE_NAME` in `infra/constants.ts`).
    static let presetCollectionsFileName = "preset-space-collections.sutto.json"
    static let customCollectionsFileName = "custom-space-collections.sutto.json"

    private let presetFileURL: URL
    private let customFileURL: URL
    private let logger = Logger(subsystem: "io.github.x7c1.SuttoMac", category: "persistence")

    /// - Parameter directory: the directory holding the collection files.
    ///   Injected so tests run against a temp directory instead of the real
    ///   Application Support; the app passes ``defaultDirectory()``.
    public init(directory: URL) {
        presetFileURL = directory.appendingPathComponent(Self.presetCollectionsFileName)
        customFileURL = directory.appendingPathComponent(Self.customCollectionsFileName)
    }

    /// `~/Library/Application Support/Sutto`.
    public static func defaultDirectory() -> URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Sutto", isDirectory: true)
    }

    public func loadPresetCollections() -> [SpaceCollection] {
        loadCollections(from: presetFileURL)
    }

    public func savePresetCollections(_ collections: [SpaceCollection]) throws {
        try saveCollections(collections, to: presetFileURL, kind: "preset")
    }

    public func loadCustomCollections() -> [SpaceCollection] {
        loadCollections(from: customFileURL)
    }

    public func saveCustomCollections(_ collections: [SpaceCollection]) throws {
        try saveCollections(collections, to: customFileURL, kind: "custom")
    }

    private func loadCollections(from fileURL: URL) -> [SpaceCollection] {
        guard FileManager.default.fileExists(atPath: fileURL.path) else {
            // First run: no file yet. Not an error.
            return []
        }
        do {
            let data = try Data(contentsOf: fileURL)
            return try JSONDecoder().decode([SpaceCollection].self, from: data)
        } catch {
            logger.error(
                """
                failed to load collections from \
                \(fileURL.path, privacy: .public): \
                \(String(describing: error), privacy: .public)
                """)
            return []
        }
    }

    private func saveCollections(
        _ collections: [SpaceCollection], to fileURL: URL, kind: String
    ) throws {
        try FileManager.default.createDirectory(
            at: fileURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        let encoder = JSONEncoder()
        // Pretty like the GNOME `JSON.stringify(_, null, 2)` output — the
        // file is user-visible; sorted keys keep rewrites diffable.
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let data = try encoder.encode(collections)

        // .atomic writes to a temporary file and renames it into place, so
        // a crash mid-write can never leave a truncated collections file.
        try data.write(to: fileURL, options: .atomic)

        logger.info(
            "saved \(collections.count) \(kind, privacy: .public) collections to \(fileURL.path, privacy: .public)"
        )
    }
}
